'use strict';
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;
const $=s=>document.querySelector(s),W=960,H=540,keys=new Set();let state='intro',time=0,last=0,score=0,wave=1,kills=0,shake=0,spawnTimer=0,nextWave=0,sound=false,audio;
let player,enemies=[],particles=[],drops=[];
const palette={o:'#172d2c',g:'#3f7c58',G:'#73ab65',l:'#b5d879',s:'#edbe91',h:'#6a4837',r:'#c95853',R:'#f48b6b',b:'#41646d',B:'#729898',w:'#e3edcf',y:'#e9d98b',p:'#66558d',P:'#aa86cc',d:'#42383f',t:'#715544',T:'#a18157',e:'#f4c66e'};
const art={hero:['......oo........','.....oggo.......','....ogGggo......','....ogGGggo.....','...oggggggoo....','....ohssso......','....oswoso......','.....ossso......','...orRRRrro.....','..oborRrobo.....','..osobBbosowo...','...oobBbo.owo...','....obBbo.owo...','....ohhho.oyo...','...obooobo.o....','...oo..ooo......'],slime:['................','.......g........','......gGl.......','.......g........','.....oooooo.....','...oogGGGlgoo...','..ogGGGGGllggo..','.ogGGGGGGGGGlgo.','.ogGwoGGGwoGGgo.','.ogGooGGGooGGgo.','.ogGGGggGGGGGgo.','..ogGGGGGGGGgo..','...oggGGGGggo...','....ooooooo.....'],bat:['................','o..............o','opo..........opo','opPo..oooo..oPpo','.opPoodPPdooPpo.','..opPPPPPPPPpo..','...oppweewppo...','....opPPPPpo....','...opoPPPPopo...','..oo..opp o..oo.','.......oo.......'],boss:['...t..........t...','..tTt........tTt..','..tTt..gg....tTt..','...tTtgGGg..tTt...','....tTtggtTtTt....','....otTTTTTTo.....','...otTTtTTtTTo....','...otTeeTeeTTo....','...otTeoToeTTo....','..ootTTTTTTTToo...','.otTotTdddTToTTo..','otTToTTdddTToTTTo.','otTootTTTTTTooTTo.','.oo.otTTtTTTo.oo..','....otTtttTTo.....','...otTTo.oTTTo....','..otTTo...oTTTo...','..oooo.....oooo...']};
function sprite(c,type,x,y,scale=3,flip=false,phase=0,flash=false){const rows=art[type];c.save();c.translate(Math.round(x),Math.round(y));c.scale(flip?-scale:scale,scale);let bob=(type==='bat'?Math.sin(phase*12)*1.5:Math.sin(phase*9)*.4);rows.forEach((row,j)=>[...row].forEach((v,i)=>{if(palette[v]){c.fillStyle=flash?'#f7f3ce':palette[v];let wing=type==='bat'&&(i<4||i>11)?Math.round(Math.sin(phase*14)*2):0;c.fillRect(i-rows[0].length/2,j-rows.length+bob+wing,1,1)}}));c.restore()}
let seed=831;function rand(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296}const decor=Array.from({length:340},()=>({x:rand()*W,y:rand()*H,r:rand(),v:rand()}));
function rect(x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(Math.round(x),Math.round(y),w,h)}
function tree(x,y,s=1){ctx.save();ctx.translate(x,y);ctx.scale(s,s);rect(-7,-30,15,43,'#182d27');rect(-3,-29,5,37,'#354333');rect(-30,-69,59,17,'#142d26');rect(-40,-55,78,22,'#173b2d');rect(-31,-37,62,15,'#1c4532');rect(-22,-80,44,17,'#1d3e2b');rect(-27,-63,48,9,'#28513a');rect(-34,-46,33,7,'#2b563b');rect(7,-34,22,6,'#2b5237');rect(-17,-73,16,5,'#325638');ctx.restore()}
function background(){rect(0,0,W,H,'#1c382d');for(const d of decor){let path=((d.x-480)**2/230**2+(d.y-280)**2/140**2)<1;rect(d.x,d.y,d.r*8+2,2,path?'#36503b':d.v>.5?'#274833':'#203f30');if(d.r>.83&&!path){rect(d.x,d.y-4,2,5,'#47724b');rect(d.x+3,d.y-2,2,3,'#395e3d')}}
ctx.fillStyle='#2e4a37';ctx.beginPath();ctx.ellipse(480,289,220,127,0,0,Math.PI*2);ctx.fill();for(const d of decor)if((d.x-480)**2/205**2+(d.y-290)**2/115**2<1)rect(d.x,d.y,7,2,'#3a523c');
for(let i=0;i<12;i++){let a=i*Math.PI/6,x=480+Math.cos(a)*112,y=285+Math.sin(a)*62;rect(x-12,y-5,24,12,'#203b32');rect(x-12,y-8,21,10,'#536953');rect(x-8,y-7,6,3,'#728063')}
rect(453,273,54,23,'#1b352f');rect(459,263,42,23,'#54664e');rect(464,258,32,14,'#819374');rect(469,259,22,4,'#afbe87');ctx.save();ctx.globalAlpha=.14+.05*Math.sin(time*2);ctx.fillStyle='#c8ff9a';ctx.beginPath();ctx.ellipse(480,261,67,34,0,0,7);ctx.fill();ctx.restore();rect(477,240,6,18,'#a8dba0');rect(473,246,14,7,'#d7edac');
for(let i=0;i<15;i++){tree(i*72-12,83+(i%3)*13,1.2);tree(i*76-10,566+(i%2)*14,1.15)}for(let i=0;i<6;i++){tree(33+(i%2)*26,145+i*72,1.1);tree(921+(i%2)*24,152+i*74,1.15)}
for(const [x,y] of [[179,149],[792,170],[210,407],[759,416]]){rect(x-13,y-7,26,14,'#142e29');rect(x-10,y-20,20,21,'#425b4e');rect(x-7,y-24,14,6,'#657c60');rect(x-4,y-17,3,10,'#91b899');rect(x+1,y-14,4,3,'#91b899');for(let i=0;i<3;i++){rect(x+15+i*6,y+7-i*3,3,5,'#c4ae83');rect(x+12+i*6,y+4-i*3,9,4,'#b06f58')}}
for(let i=0;i<24;i++){let x=(i*173+Math.sin(time*.6+i)*22+960)%960,y=(i*79+Math.cos(time*.5+i)*16)%540;ctx.globalAlpha=.25+Math.sin(time*2+i)*.2;rect(x,y,2,2,'#d7e9a0')}ctx.globalAlpha=1;
}
function beep(freq=440,duration=.08){if(!sound)return;try{audio??=new AudioContext();let o=audio.createOscillator(),g=audio.createGain();o.type='triangle';o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(freq*.5,audio.currentTime+duration);g.gain.setValueAtTime(.045,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+duration)}catch{}}
function burst(x,y,color,n=12){for(let i=0;i<n;i++)particles.push({x,y,vx:(Math.random()-.5)*180,vy:(Math.random()-.5)*180,life:.3+Math.random()*.4,color})}
function init(){player={x:480,y:350,hp:5,face:1,attack:0,cool:0,dash:0,dashCool:0,inv:0,dx:0,dy:-1};enemies=[];particles=[];drops=[];wave=1;score=0;kills=0;nextWave=0;spawnWave();updateHUD()}
function spawnWave(){let types=wave===1?['slime','slime','bat','slime']:wave===2?['slime','bat','bat','slime','bat','slime']:['boss','bat','slime','bat','slime'];types.forEach((type,i)=>{let a=i/types.length*Math.PI*2;enemies.push({type,x:480+Math.cos(a)*300,y:290+Math.sin(a)*160,hp:type==='boss'?18:type==='slime'?3:2,max:type==='boss'?18:type==='slime'?3:2,hit:0,t:Math.random()*5,charge:0,cool:2+i*.3,vx:0,vy:0})});$('#wave').textContent=`第 ${wave} / 3 波`;$('#hint').textContent=wave===3?'⚠ 枯木守望者苏醒了 · 红色蓄力时及时闪避':'✦ 击败暗影，收集散落的微光';}
function updateHUD(){$('#hearts').textContent='♥'.repeat(player.hp)+'♡'.repeat(5-player.hp);$('#score').textContent=String(score).padStart(3,'0');$('#dashbar').style.width=`${Math.max(0,1-player.dashCool/1.4)*100}%`;$('#enemies').textContent=`剩余暗影 ${enemies.length.toString().padStart(2,'0')}`}
function attack(){if(state!=='playing'||player.cool>0)return;player.attack=.22;player.cool=.33;beep(630);for(const e of enemies){let dx=e.x-player.x,dy=e.y-player.y;if(Math.hypot(dx,dy)<(e.type==='boss'?92:76)){e.hp--;e.hit=.16;let n=Math.hypot(dx,dy)||1;e.x+=dx/n*15;e.y+=dy/n*15;burst(e.x,e.y-15,'#e0dfad',9);shake=3;}}}
function dash(){if(state!=='playing'||player.dashCool>0)return;player.dash=.18;player.inv=.3;player.dashCool=1.4;beep(280,.13)}
function finish(win){state=win?'won':'dead';$('#overlay').style.display='flex';$('#overlay h2').textContent=win?'微光不灭，森林苏醒。':'休息一下，再次出发。';$('#overlay-text').innerHTML=win?`你守住了森林之心，收集了 ${score} 点微光。<br>每一份微小的勇敢，都会被森林记住。`:`本次击退 ${kills} 只暗影，收集 ${score} 点微光。<br>试试边移动边挥剑，冲刺可以短暂无敌。`;$('#start').innerHTML='再来一局 <span>↻</span>';beep(win?880:160,.4)}
function update(dt){player.cool=Math.max(0,player.cool-dt);player.attack=Math.max(0,player.attack-dt);player.inv=Math.max(0,player.inv-dt);player.dashCool=Math.max(0,player.dashCool-dt);let dx=+(keys.has('d')||keys.has('arrowright'))-+(keys.has('a')||keys.has('arrowleft')),dy=+(keys.has('s')||keys.has('arrowdown'))-+(keys.has('w')||keys.has('arrowup'));let n=Math.hypot(dx,dy);if(n){dx/=n;dy/=n;player.dx=dx;player.dy=dy;if(dx)player.face=dx>0?1:-1}if(keys.has('j'))attack();if(keys.has(' '))dash();if(player.dash>0){player.dash-=dt;dx=player.dx;dy=player.dy;burst(player.x,player.y-10,'#97cfc0',1)}let speed=player.dash>0?520:155;player.x=Math.max(85,Math.min(875,player.x+dx*speed*dt));player.y=Math.max(118,Math.min(477,player.y+dy*speed*dt));
for(const e of enemies){e.t+=dt;e.hit=Math.max(0,e.hit-dt);if(e.hp<=0)continue;let ex=player.x-e.x,ey=player.y-e.y,dist=Math.hypot(ex,ey)||1;let speed=e.type==='bat'?83:e.type==='slime'?44+Math.sin(e.t*5)*25:33;if(e.type==='boss'){e.cool-=dt;if(e.cool<=0&&e.charge===0){e.charge=1;e.vx=ex/dist;e.vy=ey/dist;beep(120,.2)}if(e.charge>0){e.charge-=dt;speed=0;if(e.charge<.35){e.x+=e.vx*320*dt;e.y+=e.vy*320*dt}if(e.charge<=0){e.charge=0;e.cool=2.8;shake=6}}}e.x+=ex/dist*speed*dt;e.y+=ey/dist*speed*dt;e.x=Math.max(80,Math.min(880,e.x));e.y=Math.max(117,Math.min(478,e.y));if(dist<(e.type==='boss'?35:24)&&player.inv<=0){player.hp--;player.inv=1.15;shake=8;burst(player.x,player.y-15,'#ec907b');beep(140);player.x=Math.max(85,Math.min(875,player.x-ex/dist*20));player.y=Math.max(118,Math.min(477,player.y-ey/dist*20));if(player.hp<=0){finish(false);break}}}
enemies=enemies.filter(e=>{if(e.hp>0)return true;kills++;score+=e.type==='boss'?100:10;burst(e.x,e.y-12,e.type==='bat'?'#ac89cc':'#b7d982',22);drops.push({x:e.x,y:e.y,t:0});return false});for(const d of drops){d.t+=dt;let dist=Math.hypot(d.x-player.x,d.y-player.y);if(dist<75){d.x+=(player.x-d.x)*dt*6;d.y+=(player.y-d.y)*dt*6}if(dist<20){d.dead=true;score+=5;player.hp=Math.min(5,player.hp+1);beep(960,.12)}}drops=drops.filter(d=>!d.dead);if(!enemies.length&&state==='playing'){nextWave+=dt;if(nextWave>1.8){if(wave===3)finish(true);else{wave++;nextWave=0;spawnWave()}}}updateHUD()}
function drawActor(a){ctx.fillStyle='#0d261c80';ctx.beginPath();ctx.ellipse(a.x,a.y+2,a.type==='boss'?28:18,6,0,0,7);ctx.fill();if(a.type==='boss'&&a.charge>.35){ctx.strokeStyle='#e67d5d';ctx.lineWidth=2;ctx.beginPath();ctx.arc(a.x,a.y,43,0,7);ctx.stroke();ctx.setLineDash([8,8]);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(a.x+a.vx*155,a.y+a.vy*155);ctx.stroke();ctx.setLineDash([])}sprite(ctx,a.type||'hero',a.x,a.y,a.type==='boss'?4:3,a.type?a.x>player.x:player.face<0,a.t||time,a.hit>0||(!a.type&&player.inv>0&&Math.sin(time*40)>0));if(a.type&&a.hp<a.max){rect(a.x-19,a.y-(a.type==='boss'?82:53),38,4,'#162e25');rect(a.x-19,a.y-(a.type==='boss'?82:53),38*a.hp/a.max,3,a.type==='boss'?'#e5a16c':'#b5d982')}}
function render(){ctx.save();if(shake>0){ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);shake*=.86}background();for(const d of drops){rect(d.x-3,d.y-8+Math.sin(time*4+d.x)*3,6,6,'#e0e9a3');rect(d.x-1,d.y-10+Math.sin(time*4+d.x)*3,2,10,'#f6f5c1')}[...enemies,player].sort((a,b)=>a.y-b.y).forEach(drawActor);if(player.attack>0){ctx.save();ctx.translate(player.x,player.y-20);ctx.strokeStyle='#e7efc7';ctx.lineWidth=7;ctx.beginPath();let angle=Math.atan2(player.dy,player.dx);ctx.arc(0,0,51,angle-1.5,angle+1.5);ctx.stroke();ctx.strokeStyle='#a7cdb4';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,60,angle-1.3,angle+1.3);ctx.stroke();ctx.restore()}for(const p of particles){ctx.globalAlpha=Math.max(0,p.life*2);rect(p.x,p.y,3,3,p.color)}ctx.globalAlpha=1;ctx.restore()}
function loop(now){let dt=Math.min((now-last)/1000,.033);last=now;if(state!=='paused'){time+=dt;if(state==='playing')update(dt);for(const p of particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt}particles=particles.filter(p=>p.life>0);render()}requestAnimationFrame(loop)}
function start(){init();state='playing';$('#overlay').style.display='none';$('#pause').textContent='Ⅱ 暂停';canvas.focus()}
function pause(){if(!['playing','paused'].includes(state))return;state=state==='playing'?'paused':'playing';$('#pause').textContent=state==='paused'?'▶ 继续':'Ⅱ 暂停';$('#overlay').style.display=state==='paused'?'flex':'none';if(state==='paused'){$('#overlay h2').textContent='在林间，歇一会儿。';$('#overlay-text').textContent='森林会等待你。';$('#start').textContent='继续冒险 →'}}
$('#start').onclick=()=>state==='paused'?pause():start();$('#restart').onclick=start;$('#pause').onclick=pause;$('#sound').onclick=()=>{sound=!sound;$('#sound').textContent=`声音：${sound?'开':'关'}`;beep(700)};window.addEventListener('keydown',e=>{let k=e.key.toLowerCase();if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();keys.add(k);if(k==='p'&&!e.repeat)pause()});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{keys.clear();if(state==='playing')pause()});canvas.addEventListener('pointerdown',()=>{canvas.focus();attack()});document.querySelectorAll('[data-key]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();keys.add(b.dataset.key);b.setPointerCapture(e.pointerId)});for(const ev of ['pointerup','pointercancel'])b.addEventListener(ev,()=>keys.delete(b.dataset.key))});
init();for(const type of ['hero','slime','boss']){let c=$('#portrait-'+type).getContext('2d');c.imageSmoothingEnabled=false;sprite(c,type,45,66,type==='boss'?3:3,false,.3)}requestAnimationFrame(loop);
